In [1]:
from timeit import timeit

import jax.numpy as jnp

from jaxparrow.tools.stencil.derivative import derivative
from jaxparrow.tools.stencil.weights import weights

%reload_ext autoreload
%autoreload 2

In [2]:
dx = jnp.arange(1000)
stencil_width = 8
stencil_weights_left = weights(dx, dx, stencil_width, True)
stencil_weights_right = weights(dx, dx, stencil_width, False)

In [3]:
derivative(jnp.linspace(.1, .5, 1000), stencil_weights_left, True)

Array([0.        , 0.0004004 , 0.0004004 , 0.0004004 , 0.00040039,
       0.0004004 , 0.0004004 , 0.0004004 , 0.0004004 , 0.0004004 ,
       0.0004004 , 0.0004004 , 0.0004004 , 0.0004004 , 0.0004004 ,
       0.0004004 , 0.00040039, 0.0004004 , 0.0004004 , 0.0004004 ,
       0.0004004 , 0.0004004 , 0.00040039, 0.0004004 , 0.0004004 ,
       0.0004004 , 0.0004004 , 0.0004004 , 0.0004004 , 0.00040039,
       0.0004004 , 0.0004004 , 0.0004004 , 0.00040039, 0.00040039,
       0.0004004 , 0.0004004 , 0.0004004 , 0.00040039, 0.0004004 ,
       0.00040039, 0.0004004 , 0.0004004 , 0.00040039, 0.0004004 ,
       0.0004004 , 0.00040041, 0.00040039, 0.00040041, 0.0004004 ,
       0.0004004 , 0.00040041, 0.00040039, 0.00040041, 0.00040039,
       0.00040039, 0.0004004 , 0.0004004 , 0.00040041, 0.0004004 ,
       0.00040039, 0.0004004 , 0.0004004 , 0.00040042, 0.0004004 ,
       0.00040039, 0.00040041, 0.00040039, 0.00040042, 0.0004004 ,
       0.00040039, 0.00040041, 0.00040039, 0.00040042, 0.00040

In [4]:
derivative(jnp.linspace(.1, .5, 1000), stencil_weights_right, False)

Array([0.0004004 , 0.0004004 , 0.0004004 , 0.00040039, 0.0004004 ,
       0.0004004 , 0.0004004 , 0.0004004 , 0.0004004 , 0.0004004 ,
       0.0004004 , 0.0004004 , 0.0004004 , 0.0004004 , 0.0004004 ,
       0.00040039, 0.0004004 , 0.0004004 , 0.0004004 , 0.0004004 ,
       0.0004004 , 0.00040039, 0.0004004 , 0.0004004 , 0.0004004 ,
       0.0004004 , 0.0004004 , 0.0004004 , 0.00040039, 0.0004004 ,
       0.0004004 , 0.0004004 , 0.00040039, 0.00040039, 0.0004004 ,
       0.0004004 , 0.0004004 , 0.00040039, 0.0004004 , 0.00040039,
       0.0004004 , 0.0004004 , 0.00040039, 0.0004004 , 0.0004004 ,
       0.00040041, 0.00040039, 0.00040041, 0.0004004 , 0.0004004 ,
       0.00040041, 0.00040039, 0.00040041, 0.00040039, 0.00040039,
       0.0004004 , 0.0004004 , 0.00040041, 0.0004004 , 0.00040039,
       0.0004004 , 0.0004004 , 0.00040042, 0.0004004 , 0.00040039,
       0.00040041, 0.00040039, 0.00040042, 0.0004004 , 0.00040039,
       0.00040041, 0.00040039, 0.00040042, 0.0004004 , 0.00040

In [5]:
derivative(jnp.ones(1000), stencil_weights_left, True)

Array([ 0.0000000e+00,  0.0000000e+00, -4.0978193e-08,  2.0954758e-08,
       -2.2526365e-08, -2.2526365e-08, -2.2526365e-08, -2.2526365e-08,
       -2.2526365e-08, -2.2526365e-08, -2.2526365e-08, -2.2526365e-08,
       -2.2526365e-08, -2.2526365e-08, -2.2526365e-08, -2.2526365e-08,
       -2.2526365e-08, -2.2526365e-08, -2.2526365e-08, -2.2526365e-08,
       -2.2526365e-08, -2.2526365e-08, -2.2526365e-08, -2.2526365e-08,
       -2.2526365e-08, -2.2526365e-08, -2.2526365e-08, -2.2526365e-08,
       -2.2526365e-08, -2.2526365e-08, -2.2526365e-08, -2.2526365e-08,
       -2.2526365e-08, -2.2526365e-08, -2.2526365e-08, -2.2526365e-08,
       -2.2526365e-08, -2.2526365e-08, -2.2526365e-08, -2.2526365e-08,
       -2.2526365e-08, -2.2526365e-08, -2.2526365e-08, -2.2526365e-08,
       -2.2526365e-08, -2.2526365e-08, -2.2526365e-08, -2.2526365e-08,
       -2.2526365e-08, -2.2526365e-08, -2.2526365e-08, -2.2526365e-08,
       -2.2526365e-08, -2.2526365e-08, -2.2526365e-08, -2.2526365e-08,
      

In [6]:
derivative(jnp.arange(1000), stencil_weights_left, True)

Array([0.        , 1.        , 1.        , 1.        , 0.9999999 ,
       0.99999994, 1.        , 1.0000002 , 0.9999998 , 1.0000004 ,
       1.0000004 , 0.99999964, 0.9999997 , 0.99999976, 0.9999998 ,
       0.9999999 , 0.99999917, 1.0000001 , 0.9999993 , 1.0000004 ,
       0.9999995 , 1.0000006 , 0.99999964, 1.0000007 , 0.99999994,
       0.99999905, 1.        , 0.99999917, 1.0000004 , 0.9999994 ,
       0.99999857, 0.9999996 , 1.0000006 , 1.0000017 , 0.9999989 ,
       0.99999994, 1.000001  , 0.99999833, 0.99999934, 1.0000004 ,
       1.0000013 , 0.9999987 , 0.9999997 , 1.0000007 , 0.9999979 ,
       0.9999991 , 1.0000001 , 1.0000011 , 0.99999833, 0.99999934,
       1.0000005 , 0.9999977 , 0.99999875, 0.9999999 , 1.0000008 ,
       0.9999981 , 0.9999991 , 1.0000002 , 1.0000013 , 0.9999985 ,
       0.9999957 , 1.0000006 , 0.99999785, 1.0000027 , 0.9999999 ,
       0.9999972 , 1.000002  , 0.9999993 , 0.9999965 , 1.0000014 ,
       0.9999986 , 0.9999958 , 1.0000007 , 0.999998  , 1.00000

In [7]:
field = jnp.linspace(.1, .5, 1000)

In [8]:
%timeit derivative(field, stencil_weights_left, True)

7.99 µs ± 229 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
