In [1]:
from timeit import timeit

import jax.numpy as jnp

from mask import mask

%reload_ext autoreload
%autoreload 2

In [2]:
no_land = jnp.ones(10)
with_nan = jnp.ones(10).at[4].set(jnp.nan)
with_inf = jnp.ones(10).at[1].set(jnp.inf)

In [3]:
no_land, with_inf, with_nan

(Array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 Array([ 1., inf,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32),
 Array([ 1.,  1.,  1.,  1., nan,  1.,  1.,  1.,  1.,  1.], dtype=float32))

In [4]:
mask(no_land, 4, True), mask(with_inf, 4, True), mask(with_nan, 4, True)

(Array([[False,  True, False, False, False, False, False, False, False,
          True],
        [False, False,  True, False, False, False, False, False,  True,
         False],
        [False, False, False,  True, False, False, False,  True, False,
         False],
        [False, False, False, False,  True,  True,  True, False, False,
         False]], dtype=bool),
 Array([[False, False, False,  True, False, False, False, False, False,
          True],
        [False, False, False, False,  True, False, False, False,  True,
         False],
        [False, False, False, False, False,  True, False,  True, False,
         False],
        [False, False, False, False, False, False,  True, False, False,
         False]], dtype=bool),
 Array([[False,  True, False,  True, False, False,  True, False, False,
          True],
        [False, False,  True, False, False, False, False,  True,  True,
         False],
        [False, False, False, False, False, False, False, False, False,
         F

In [5]:
mask(no_land, 4, False), mask(with_inf, 4, False), mask(with_nan, 4, False)

(Array([[ True, False, False, False, False, False, False, False,  True,
         False],
        [False,  True, False, False, False, False, False,  True, False,
         False],
        [False, False,  True, False, False, False,  True, False, False,
         False],
        [False, False, False,  True,  True,  True, False, False, False,
         False]], dtype=bool),
 Array([[False, False,  True, False, False, False, False, False,  True,
         False],
        [False, False, False,  True, False, False, False,  True, False,
         False],
        [False, False, False, False,  True, False,  True, False, False,
         False],
        [False, False, False, False, False,  True, False, False, False,
         False]], dtype=bool),
 Array([[ True, False,  True, False, False,  True, False, False,  True,
         False],
        [False,  True, False, False, False, False,  True,  True, False,
         False],
        [False, False, False, False, False, False, False, False, False,
         F

In [6]:
%timeit mask(no_land, 4, True)

906 µs ± 8.26 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
